version: '3.6'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=testing
      - APP_SETTINGS=project.config.TestingConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test

    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  teams:
    build:
      context: ./services/teams
      dockerfile: Dockerfile-dev
    volumes:
      - './services/teams:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=testing
      - APP_SETTINGS=project.config.TestingConfig
      - DATABASE_URL=postgres://postgres:postgres@teams-db:5432/teams_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@teams-db:5432/teams_test

    depends_on:
      - teams-db

  teams-db:
    build:
      context: ./services/teams/project/db
      dockerfile: Dockerfile
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  matches:
    build:
      context: ./services/matches
      dockerfile: Dockerfile-dev
    volumes:
      - './services/matches:/usr/src/app'
    ports:
      - 5003:5000
    environment:
      - FLASK_ENV=testing
      - APP_SETTINGS=project.config.TestingConfig
      - DATABASE_URL=postgres://postgres:postgres@matches-db:5432/matches_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@matches-db:5432/matches_test

    depends_on:
      - matches-db

  matches-db:
    build:
      context: ./services/matches/project/db
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - './services/client:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=testing
      - APP_SETTINGS=project.config.TestingConfig
      - DATABASE_URL=postgres://postgres:postgres@client-db:5432/client_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@client-db:5432/client_test

    depends_on:
      - client-db

  client-db:
    build:
      context: ./services/client/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - teams
      - matches
      - client

